%close all

clims = [-30 30];
figure(3);
subplot(1,2,1);
imagesc(blinkData_csPlus, clims);
colorbar;
title([mouse ' SessionType' sessionType ' Session' session ' CS+ Trials'],...
    'FontSize',20,...
    'FontWeight','bold');
xlabel('Time (/10 ms)',...
    'FontSize',20,...
    'FontWeight','bold');
xt = get(gca, 'XTick');
set(gca, 'FontSize', 20)
ylabel('Trials',...
    'FontSize',20,...
    'FontWeight','bold');
yt = get(gca, 'YTick');
set(gca, 'FontSize', 20)
%figure(4);
subplot(1,2,2);
imagesc(blinkData_csMinus, clims);
colorbar;
title([mouse ' SessionType' sessionType ' Session' session ' CS- Trials'],...
    'FontSize',20,...
    'FontWeight','bold');
xlabel('Time (/10 ms)',...
    'FontSize',20,...
    'FontWeight','bold');
xt = get(gca, 'XTick');
set(gca, 'FontSize', 20)
ylabel('Trials',...
    'FontSize',20,...
    'FontWeight','bold');
yt = get(gca, 'YTick');
set(gca, 'FontSize', 20)

figure(4);
subplot(1,2,1);
imagesc(blinkData_csPlus_fullFiltered, clims);
colorbar;
title([mouse ' SessionType' sessionType ' Session' session ' CS+ Trials'],...
    'FontSize',20,...
    'FontWeight','bold');
xlabel('Time (/10 ms)',...
    'FontSize',20,...
    'FontWeight','bold');
xt = get(gca, 'XTick');
set(gca, 'FontSize', 20)
ylabel('Trials',...
    'FontSize',20,...
    'FontWeight','bold');
yt = get(gca, 'YTick');
set(gca, 'FontSize', 20)
%figure(6);
subplot(1,2,2);
imagesc(blinkData_csMinus_fullFiltered, clims);
colorbar;
title([mouse ' SessionType' sessionType ' Session' session ' CS- Trials'],...
    'FontSize',20,...
    'FontWeight','bold');
xlabel('Time (/10 ms)',...
    'FontSize',20,...
    'FontWeight','bold');
xt = get(gca, 'XTick');
set(gca, 'FontSize', 20)
ylabel('Trials',...
    'FontSize',20,...
    'FontWeight','bold');
yt = get(gca, 'YTick');
set(gca, 'FontSize', 20)